### ISSUE TITLE
Can I replace the 3*3 convolution with DSConv?

### ISSUE THREAD

**Issue by Claraeunice** [YaoleiQi/DSCNet#14]
You've done such a great job that you've attracted a large number of enthusiasts like me to your work!
I would like to know what to do if I use DSConv to replace the 3*3 convolution.
`class DSConv(nn.Layer):

    def __init__(self, in_ch, out_ch, kernel_size, extend_scope, morph,
                 if_offset, device):`
I don't know what to do with the parameters morph, if_offset, and device.
Very much looking forward to your reply!

**Comment by z-anya** [comment]
hi，Have you solved the problem?I have the same question.

**Comment by Claraeunice** [comment]
> hi，Have you solved the problem?I have the same question.

But I've noticed that the serpentine convolution replacing the 3*3 convolution doesn't seem to be able to use the offset convolution inside (if if_offset), so you can see if that's the case

**Comment by YaoleiQi** [comment]
I'm sorry for not being able to respond to your messages promptly due to the recent heavy workload. Regarding the deformation parameters: "morph," "if_offset," and "device" represent the direction of deformation (along the x-axis or y-axis), whether deformation is applied, and whether the computation is accelerated on CUDA, respectively. The previously open-sourced code leaned more toward functional implementation and indeed had some imperfect encapsulation.

During this time, we have been working on improving the encapsulation and submitting to some open-source repositories. If we successfully establish it in the future, we will notify you promptly. As for detailed code explanations and the training process, we will consider providing updates if we have more time in the future. Thank you very much for your understanding, and we look forward to keeping you informed of our progress. If you have any further questions or need assistance, please feel free to let us know.
